Repository CSC207-2022F-UofT/course-project-wanna-date, pull requests merged in 2022-12, with the labels that each got.

#48 Added test cases and modified feature in Registration UseCase
  src/main/java/frameworksDrivers/database.csv
  src/main/java/useCase/RegistrationManager.java
  src/test/java/useCase/LoginManagerTest.java
  src/test/java/useCase/RegistrationManagerTest.java
  src/test/java/useCase/ViewProfileInputManagerTest.java
Labels: enhancement

#54 4a update 01
  build.gradle
  src/main/java/interfaceAdapters/RecController.java
  src/main/java/interfaceAdapters/RecPresenter.java
  src/main/java/useCase/RecInputBoundary.java
  src/main/java/useCase/RecOutputBoundary.java
  src/main/java/useCase/Recommendation.java
  src/main/java/useCase/RecommendedProfiles.java
  src/test/java/useCase/recommendationTest.java
Labels: documentation, enhancement

#67 4a update 03
  .idea/misc.xml
  src/main/java/UI/RecBtnManager.java
  src/main/java/UI/ViewProfilePage.java
  src/main/java/entities/ComparingProfile.java
  src/main/java/interfaceAdapters/RecController.java
  src/main/java/interfaceAdapters/RecShowRecBoundary.java
  src/main/java/useCase/CompProfileFactory.java
  src/main/java/useCase/RecDataGetFacade.java
  src/main/java/useCase/RecDataGetter.java
  src/main/java/useCase/RecInputBoundary.java
  src/main/java/useCase/RecOutProfile.java
  src/main/java/useCase/RecOutputBoundary.java
  src/main/java/useCase/RecOutputBuilder.java
  src/main/java/useCase/RecOutputBuilder1.java
  src/main/java/useCase/Recommendation.java
  src/test/java/interface_adapters/FakeRecPresenter.java
  src/test/java/useCase/RecommendationTest.java
Labels: bug, enhancement
